# Generated by Django 5.2.7 on 2025-10-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='yil',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
